stability update
File "/usr/local/lib/python3.5/dist-packages/autobahn/websocket/protocol.py", line 2203, in sendMessage
    assert type(payload) == six.binary_type, '"payload" must have type bytes, but was "{}"'.format(type(payload))
builtins.AssertionError: "payload" must have type bytes, but was "<class 'str'>"

Changed to take bytes message instead of converted string